//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfpaLunch
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandeProduit
    {
        public int IdCommande { get; set; }
        public int IdProduit { get; set; }
        public decimal Prix { get; set; }
        public int Quantite { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
