//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfpaLunch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int IdOperation { get; set; }
        public int IdUtilisateur { get; set; }
        public decimal Montant { get; set; }
        public int IdTypeVersement { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual TypeVersement TypeVersement { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
